{"ast":null,"code":"import _classCallCheck from\"D:/HOC_CUNG_HOI_DAN_IT/practiceReact/React-Practice/node_modules/@babel/runtime/helpers/esm/classCallCheck.js\";import _createClass from\"D:/HOC_CUNG_HOI_DAN_IT/practiceReact/React-Practice/node_modules/@babel/runtime/helpers/esm/createClass.js\";import _inherits from\"D:/HOC_CUNG_HOI_DAN_IT/practiceReact/React-Practice/node_modules/@babel/runtime/helpers/esm/inherits.js\";import _createSuper from\"D:/HOC_CUNG_HOI_DAN_IT/practiceReact/React-Practice/node_modules/@babel/runtime/helpers/esm/createSuper.js\";import React from'react';import{jsx as _jsx}from\"react/jsx-runtime\";var ErrorBoundary=/*#__PURE__*/function(_React$Component){_inherits(ErrorBoundary,_React$Component);var _super=_createSuper(ErrorBoundary);function ErrorBoundary(props){var _this;_classCallCheck(this,ErrorBoundary);_this=_super.call(this,props);_this.state={hasError:false};return _this;}_createClass(ErrorBoundary,[{key:\"componentDidCatch\",value:function componentDidCatch(error,errorInfo){// You can also log the error to an error reporting service\n//   logErrorToMyService(error, errorInfo);\n}},{key:\"render\",value:function render(){if(this.state.hasError){// You can render any custom fallback UI\nreturn/*#__PURE__*/_jsx(\"h1\",{children:\"Something went wrong.\"});}return this.props.children;}}],[{key:\"getDerivedStateFromError\",value:function getDerivedStateFromError(error){// Update state so the next render will show the fallback UI.\nreturn{hasError:true};}}]);return ErrorBoundary;}(React.Component);export default ErrorBoundary;","map":{"version":3,"names":["React","jsx","_jsx","ErrorBoundary","_React$Component","_inherits","_super","_createSuper","props","_this","_classCallCheck","call","state","hasError","_createClass","key","value","componentDidCatch","error","errorInfo","render","children","getDerivedStateFromError","Component"],"sources":["D:/HOC_CUNG_HOI_DAN_IT/practiceReact/React-Practice/src/component/ErrorBoundary/Error.js"],"sourcesContent":["import React from 'react';\r\n\r\nclass ErrorBoundary extends React.Component {\r\n    constructor(props) {\r\n      super(props);\r\n      this.state = { hasError: false };\r\n    }\r\n  \r\n    static getDerivedStateFromError(error) {\r\n      // Update state so the next render will show the fallback UI.\r\n      return { hasError: true };\r\n    }\r\n  \r\n    componentDidCatch(error, errorInfo) {\r\n      // You can also log the error to an error reporting service\r\n    //   logErrorToMyService(error, errorInfo);\r\n    }\r\n  \r\n    render() {\r\n      if (this.state.hasError) {\r\n        // You can render any custom fallback UI\r\n        return <h1>Something went wrong.</h1>;\r\n      }\r\n  \r\n      return this.props.children; \r\n    }\r\n  }\r\n\r\nexport default ErrorBoundary;"],"mappings":"ohBAAA,MAAO,CAAAA,KAAK,KAAM,OAAO,CAAC,OAAAC,GAAA,IAAAC,IAAA,4BAEpB,CAAAC,aAAa,uBAAAC,gBAAA,EAAAC,SAAA,CAAAF,aAAA,CAAAC,gBAAA,MAAAE,MAAA,CAAAC,YAAA,CAAAJ,aAAA,EACf,SAAAA,cAAYK,KAAK,CAAE,KAAAC,KAAA,CAAAC,eAAA,MAAAP,aAAA,EACjBM,KAAA,CAAAH,MAAA,CAAAK,IAAA,MAAMH,KAAK,EACXC,KAAA,CAAKG,KAAK,CAAG,CAAEC,QAAQ,CAAE,KAAM,CAAC,CAAC,OAAAJ,KAAA,CACnC,CAACK,YAAA,CAAAX,aAAA,GAAAY,GAAA,qBAAAC,KAAA,CAOD,SAAAC,kBAAkBC,KAAK,CAAEC,SAAS,CAAE,CAClC;AACF;AAAA,CACC,GAAAJ,GAAA,UAAAC,KAAA,CAED,SAAAI,OAAA,CAAS,CACP,GAAI,IAAI,CAACR,KAAK,CAACC,QAAQ,CAAE,CACvB;AACA,mBAAOX,IAAA,OAAAmB,QAAA,CAAI,uBAAqB,CAAI,CAAC,CACvC,CAEA,MAAO,KAAI,CAACb,KAAK,CAACa,QAAQ,CAC5B,CAAC,KAAAN,GAAA,4BAAAC,KAAA,CAjBD,SAAAM,yBAAgCJ,KAAK,CAAE,CACrC;AACA,MAAO,CAAEL,QAAQ,CAAE,IAAK,CAAC,CAC3B,CAAC,WAAAV,aAAA,GATuBH,KAAK,CAACuB,SAAS,EA0B3C,cAAe,CAAApB,aAAa"},"metadata":{},"sourceType":"module"}